version: '3.6'
networks:
  web:
    external: true
  internal:
    external: false

services:
  moneylogger_back:
    container_name: moneylogger_back
    image: moneylogger_back
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      SECRET_KEY:
      POSTGRES_PASSWORD:
      EMAIL_PASSWORD:
      SECURITY_PASSWORD_SALT:
    volumes:
      - volume_moneylogger_downloads:/srv/downloads
    depends_on:
      - moneylogger_postgres_db
    networks:
      - web
      - internal

  moneylogger_front:
    container_name: moneylogger_front
    image: moneylogger_front
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moneylogger.entrypoints=https"
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.http.routers.moneylogger.tls=true"
      - "traefik.http.routers.moneylogger.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.moneylogger.rule=Host(`money.nezvanov.ru`)"
    networks:
      - web
      - internal

  moneylogger_postgres_db:
    container_name: moneylogger_postgres_db
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: moneylogger
      POSTGRES_DB: moneylogger
    volumes:
      - volume_moneylogger_postgres_db:/var/lib/postgresql/data
    networks:
      - internal

  adminer_moneylogger_postgres_db:
    container_name: adminer_moneylogger_postgres_db
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 82:8080
    environment:
      ADMINER_DEFAULT_SERVER: moneylogger_postgres_db
    networks:
      - internal

volumes:
  volume_moneylogger_postgres_db:
  volume_moneylogger_downloads: