version: '3.6'
networks:
  web:
    external: true
  internal:
    external: false

services:
  moneylogger_app:
    container_name: moneylogger_app
    image: moneylogger_app
    restart: unless-stopped
    environment:
      SECRET_KEY:
      POSTGRES_PASSWORD:
      EMAIL_PASSWORD:
      SECURITY_PASSWORD_SALT:
    ports:
      - 81:8888
    depends_on:
      - moneylogger_postgres_db
    networks:
      - web
      - internal

  moneylogger_postgres_db:
    container_name: moneylogger_postgres_db
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: moneylogger
      POSTGRES_DB: moneylogger
    volumes:
      - volume_moneylogger_postgres_db:/var/lib/postgresql/data
    networks:
      - internal

  adminer_moneylogger_postgres_db:
    container_name: adminer_moneylogger_postgres_db
    image: adminer:4.8.1
    restart: always
    ports:
      - 82:8080
    environment:
      ADMINER_DEFAULT_SERVER: moneylogger_postgres_db
    networks:
      - internal

#  moneylogger_jupyter:
#    container_name: moneylogger_jupyter
#    image: jupyter/minimal-notebook
#    restart: unless-stopped
#    environment:
#      SECRET_KEY:
#      POSTGRES_PASSWORD:
#      EMAIL_PASSWORD:
#    volumes:
#      - .://home/jovyan/work
#    ports:
#      - 83:8888
#    networks:
#      - internal

volumes:
  volume_moneylogger_postgres_db: