version: '3.6'
networks:
  web:
    external: true
  internal:
    external: false

services:
  moneylogger_back:
    container_name: moneylogger_back
    image: moneylogger_back
    restart: unless-stopped
    environment:
      FLASK_APP: app.py
      SECRET_KEY:
      POSTGRES_PASSWORD:
      EMAIL_PASSWORD:
      SECURITY_PASSWORD_SALT:
    volumes:
      - volume_moneylogger_downloads:/srv/downloads
    ports:
      - 81:80
    depends_on:
      - moneylogger_postgres_db
    networks:
      - web
      - internal

  moneylogger_front:
    container_name: moneylogger_front
    image: moneylogger_front
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - web
      - internal

#  moneylogger_celery:
#    container_name: moneylogger_celery
#    image: moneylogger_back
#    restart: unless-stopped
#    command: celery -A tasks.celery worker -l INFO -c 1 --max-memory-per-child 1000000 --max-tasks-per-child 50
#    environment:
#      SECRET_KEY:
#      POSTGRES_PASSWORD:
#      EMAIL_PASSWORD:
#      SECURITY_PASSWORD_SALT:
#    depends_on:
#      - moneylogger_postgres_db
#      - moneylogger_redis
#    networks:
#      - internal

  moneylogger_postgres_db:
    container_name: moneylogger_postgres_db
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: moneylogger
      POSTGRES_DB: moneylogger
    volumes:
      - volume_moneylogger_postgres_db:/var/lib/postgresql/data
    networks:
      - internal

  adminer_moneylogger_postgres_db:
    container_name: adminer_moneylogger_postgres_db
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 82:8080
    environment:
      ADMINER_DEFAULT_SERVER: moneylogger_postgres_db
    networks:
      - internal

#  moneylogger_jupyter:
#    container_name: moneylogger_jupyter
#    image: jupyter/minimal-notebook
#    restart: unless-stopped
#    environment:
#      SECRET_KEY:
#      POSTGRES_PASSWORD:
#      EMAIL_PASSWORD:
#    volumes:
#      - .://home/jovyan/work
#    ports:
#      - 83:8888
#    networks:
#      - internal

#  moneylogger_redis:
#    container_name: moneylogger_redis
#    image: redis:5.0.3-alpine
#    restart: unless-stopped
#    networks:
#      - internal

volumes:
  volume_moneylogger_postgres_db:
  volume_moneylogger_downloads: