postgres:
  host: moneylogger_postgres_db
  port: 5432
  user: moneylogger
  database: moneylogger
email:
  host: smtp.mail.ru
  port: 465
  use_ssl: True
  login: moneylogger@nezvanov.ru
  sender_name: MoneyLogger
