"""empty message

Revision ID: 1aae242c79e4
Revises: 62e0540ab8f5
Create Date: 2022-10-13 08:48:18.939819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aae242c79e4'
down_revision = '62e0540ab8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('patronymic', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'patronymic')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
