"""empty message

Revision ID: d78c5289e854
Revises: 8b55ae54aa6a
Create Date: 2022-10-18 16:47:59.079512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78c5289e854'
down_revision = '8b55ae54aa6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('categories', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
