"""empty message

Revision ID: e129cc6ef5f9
Revises: 022e0d2b3185
Create Date: 2022-10-13 07:17:42.955888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e129cc6ef5f9'
down_revision = '022e0d2b3185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolexuser',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('role_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_user_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='role_user_user_id_fkey')
    )
    op.drop_table('rolexuser')
    # ### end Alembic commands ###
